# Generated by Django 5.1.4 on 2025-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=50, unique=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('release_yr', models.PositiveSmallIntegerField()),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
