"""
Django settings for index project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# JWT settings
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)$^fckk7j66ww=3(l8fwbav%fkly2$y&l(-ar(iio!^&x2fnqn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    # Default  Authentication
    # 'rest_framework.authtoken',  # Required for dj-rest-auth
    # 'dj_rest_auth',
    # 'allauth',
    'allauth.account',  # Required for registration
    # 'allauth.socialaccount',
    # 'django.contrib.sites',   # Required for allauth

    # Custom
    'movies',
    'users',
    'genres',
    'reviews'

]

# SITE_ID = 1

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }

# # dj-rest-auth settings
# REST_USE_JWT = True

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': 'your-secret-key',
# }


MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    
    # Other middleware classes
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'index.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'index.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # Specifies the PostgreSQL backend
#         'NAME': 'movieReviewDB',                   # Database name (DB in dbConfig)
#         'USER': 'postgres',                        # Database user (USER in dbConfig)
#         'PASSWORD': '12345678',                       # Password (PASSWORD in dbConfig: Remember to change this to fit your DB)
#         'HOST': '127.0.0.1',                       # Host (HOST in dbConfig)
#         'PORT': '5432',                            # Default PostgreSQL port
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Specifies the PostgreSQL backend
        'NAME': 'movieReviewDB',                   # Database name (DB in dbConfig)
        'USER': 'postgres',                        # Database user (USER in dbConfig)
        'PASSWORD': 'alina',                       # Password (PASSWORD in dbConfig: Remember to change this to fit your DB)
        'HOST': '127.0.0.1',                       # Host (HOST in dbConfig)
        'PORT': '5432',                            # Default PostgreSQL port
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # Specifies the PostgreSQL backend
#         'NAME': 'movieReviewDB',                   # Database name (DB in dbConfig)
#         'USER': 'postgres',                        # Database user (USER in dbConfig)
#         'PASSWORD': 'admin',                       # Password (PASSWORD in dbConfig: Remember to change this to fit your DB)
#         'HOST': '127.0.0.1',                       # Host (HOST in dbConfig)
#         'PORT': '5432',                            # Default PostgreSQL port
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
