# Generated by Django 5.1.4 on 2025-01-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('review', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings_reviews',
                'managed': False,
            },
        ),
    ]
