# Generated by Django 5.1.4 on 2025-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
    ]
